Traceback (most recent call last):
  File "/home/christoph/anaconda3/envs/science-career-tempenv/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/christoph/anaconda3/envs/science-career-tempenv/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/christoph/mag_sample/src/dataprep/main/load_proquest/magfos_to_db.py", line 73, in <module>
    con.close()
sqlite3.ProgrammingError: Cannot operate on a closed database.
Running ANALYZE... 

